name: Development Task
description: "Add a anticipated development task"
labels: ["development"]
body:
  - type: markdown
    attributes:
      value: |
        Form for general development tasks.
  - type: textarea
    id: 
    attributes:
      label: Description
      description: "Description of the task at hand."
      placeholder: |
        ## Description
        
      value: |
        ## Description
        
        
        
    validations:
      required: true
