name: Auto approve

on:
  pull_request:
    branches:
    - develop

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'github-actions[bot]' || github.actor == 'dti-devops' || github.actor == 'github-actions'
      with:
        github-token: "${{ secrets.DTI_DEVOPS_TOKEN }}"