##########################################################################
#
#  Will auto-merge pull request with the label "automerge"
#
##########################################################################

name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches:
      - develop
      - tc01d
      - tc02d
      - tc03d
  pull_request_review:
    types:
      - submitted
    branches:
      - develop
      - tc01d
      - tc02d
      - tc03d
  check_suite:
    types:
      - completed
    branches:
      - develop
      - tc01d
      - tc02d
      - tc03d
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Actor $GITHUB_ACTOR"
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.DTI_DEVOPS_TOKEN }}"
          MERGE_METHOD: "merge"
          MERGE_REQUIRED_APPROVALS: "1"
          MERGE_DELETE_BRANCH: true
