on:
  workflow_call:
    inputs:
      tenant:
        description: 'Target C3 Tenant'     
        required: true
        type: string
      tag:
        description: 'target C3 Tag'
        required: true
        type: string
      domain:
        description: 'Web domain for tag'
        required: true
        type: string
      c3repo:
        description: 'Repo directory containing package'
        required: true
        type: string
      package:
        description: 'Name of package to be provisioned'
        required: true
        type: string

########################################################################        
# Settings for this workflow:
# Modify the following settings to match target C3 tag and local 
# c3repo and package names. 
########################################################################
env:
  DTI_PROVISIONER_VERSION: main
  TAG: ${{ github.event.inputs.tag }}
  TENANT: ${{ github.event.inputs.tenant }}
  DOMAIN: ${{ github.event.inputs.domain }}
  C3REPO: ${{ github.event.inputs.c3repo }}
  PACKAGE: ${{ github.event.inputs.package }}
########################################################################
# You should not need to edit below here, unless altering the workflow
########################################################################
  PYTHON_VERSION: 3.9 # For running pytest "locally", not for C3 env.

jobs:
  # Gate to check for changed files within the c3repo
  c3changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      c3repo: ${{ steps.filter.outputs.c3repo }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          c3repo:
            - 'c3training/**'
  provision:
    name: Provision to ${{ github.event.inputs.tag }}
    needs: c3changes
    if: ${{ needs.c3changes.outputs.c3repo == 'true' }}
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout this repo
        uses: actions/checkout@v2
        
      - name: Check out C3 CLI
        uses: actions/checkout@v2  
        with:
          repository: c3aidti/C3-CLI
          token: ${{ secrets.DTI_DEVOPS_TOKEN }}
          path: c3cli
          
      - name: Install C3 CLI Environment
        run: |
          ./c3cli/c3 install
        
      - name: Checkout DTI Provisioner repo
        uses: actions/checkout@v2
        with:
          repository: c3aidti/dti-provisioner
          ref: ${{ env.DTI_PROVISIONER_VERSION }}
          token: ${{ secrets.DTI_DEVOPS_TOKEN }} # stored in GitHub secrets
          path: dti-provisioner
          
      - name: Run Provisioner
        uses: ./dti-provisioner
        env:
          GPG_PASS: ${{ secrets.DTI_DEVOPS_GPG }}
        with:
          tenant: ${{ github.event.inputs.tenant }}
          tag: ${{ github.event.inputs.tag }}
          domain: ${{ github.event.inputs.domain }}
          package: ${{ github.event.inputs.package }}
          c3repo: ${{ github.event.inputs.c3repo }}
