on:
  pull_request:
    branches:
    - tc04d
  workflow_dispatch:
    inputs:
      options:
        description: "Additional options to pass to provisioner (eg: -E, -r)"
        required: false
        default: ""
        
########################################################################        
# Settings for this workflow:
# Modify the settings under the "with" list to match target C3 tag 
# and local c3repo and package names. 
#######################################################################
jobs:
  call-provisioner:
    uses: c3aidti/training-space-ids/.github/workflows/provision.yml@main
    with:
      tenant: 'dev'
      tag: 'tc04d'
      branch: 'tc04d'
      domain: 'c3dti.ai'
      package: 'dti-jupyter'
      c3repo: 'training'
      options: ''
      version: 'main'
    secrets:
      token: ${{ secrets.DTI_DEVOPS_TOKEN }}
      gpg: ${{ secrets.DTI_DEVOPS_GPG }}
