on:
  schedule:
    - cron:  '30 9 * * *'

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Reset develop
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Sync develop to main'
          labels: |
            automated pr
          token: ${{secrets.GITHUB_TOKEN}}
          branch: develop-to--update